language: minimal

services:
  - docker

script: |
  docker run --rm \
    -v $(pwd):/tmp \
    -w /tmp \
    hashicorp/packer:light \
    validate *.json && packer inspect *.json

deploy:
- provider: script
  script: |
    docker run --rm --entrypoint bash \
      -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
      -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
      -v $(pwd):/tmp \
      -w /tmp \
      hashicorp/packer:light \
      -c "./build_images.sh"
  skip_cleanup: true
  on:
    branch: master