language: minimal

services:
  - docker

script: |
  docker run --rm \
    -v $(pwd):/tmp \
    -w /tmp \
    hashicorp/packer:light \
    validate *.json && packer inspect *.json

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
<<<<<<< HEAD
    script: docker run --rm --entrypoint bash -e AWS_ACCESS_KEY_ID="$AWS_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_KEY" -v $(pwd):/tmp -w /tmp hashicorp/packer:light -c "./build_images.sh"
=======
    script: >-
      docker run --rm --entrypoint bash \
        -e AWS_ACCESS_KEY_ID="$AWS_ID" \
        -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_KEY" \
        -v $(pwd):/tmp \
        -w /tmp \
        hashicorp/packer:light \
        -c "./build_images.sh"
>>>>>>> 738fd7330d99a2829ff650311f3091fb4083eef4
