language: minimal

services:
  - docker

script: |
  docker run --rm \
    -v $(pwd):/tmp \
    -w /tmp \
    hashicorp/packer:light \
    validate -var aws_access_key="test" -var aws_secret_key="test" .

# deploy:
#   - provider: script
#     skip_cleanup: true
#     on:
#       branch: master
#     script: docker run --rm --entrypoint bash -e AWS_ACCESS_KEY_ID="$AWS_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_KEY" -v $(pwd):/tmp -w /tmp hashicorp/packer:light -c "./build_images.sh"
